#pragma once 
#include "exenv.h"
#include "reformat.h"
#include <stdio.h>
void handle_lbi();
void handle_lwi();
void handle_ldi();
void handle_lqi();
void handle_lf1i();
void handle_lf2i();
void handle_lad();
void handle_lai();
void handle_lb();
void handle_lw();
void handle_ld();
void handle_lq();
void handle_lf1();
void handle_lf2();
